import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { StackProvider, StackTheme } from "@stackframe/stack";

import { NavBar } from "@/components/nav/nav-bar";

import { stackServerApp } from "@/stack/server";
// import { stackClientApp } from "@/stack/client";

import "./globals.css";

//
//

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StackProvider
          app={stackServerApp}
          // in workshop they used stackClientApp (needt to learn more about this, I assume it is client component)
          // app={stackClientApp}
        >
          <NavBar />
          <StackTheme>{children}</StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
